#include "gpio_output.h"
#include "gpio_input.h"

/**
  * 函数功能: 板载按键IO引脚初始化.
  * 输入参数: 无
  * 返 回 值: 无
  * 说    明：使用宏定义方法代替具体引脚号，方便程序移植，只要简单修改bsp_gpio.h
  *           文件相关宏定义就可以方便修改引脚。
  */
void OUTPUT_GPIO_Init(void)
{
	/* 定义IO硬件初始化结构体变量 */
	GPIO_InitTypeDef GPIO_InitStruct={0};

	/* 使能(开启)KEY引脚对应IO端口时钟 */  
	OUTPUT1_RCC_CLK_ENABLE();
	OUTPUT2_RCC_CLK_ENABLE();
	OUTPUT3_RCC_CLK_ENABLE();
	OUTPUT4_RCC_CLK_ENABLE();
	
	OUTPUT5_RCC_CLK_ENABLE();
	OUTPUT6_RCC_CLK_ENABLE();
	OUTPUT7_RCC_CLK_ENABLE();
	OUTPUT8_RCC_CLK_ENABLE();
	OUTPUT9_RCC_CLK_ENABLE();
	OUTPUT10_RCC_CLK_ENABLE();
	OUTPUT11_RCC_CLK_ENABLE();
	OUTPUT12_RCC_CLK_ENABLE();
	OUTPUT13_RCC_CLK_ENABLE();
	OUTPUT14_RCC_CLK_ENABLE();
	OUTPUT15_RCC_CLK_ENABLE();
	OUTPUT16_RCC_CLK_ENABLE();

	HAL_GPIO_WritePin(OUTPUT1_GPIO,  OUTPUT1_GPIO_PIN,  GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT2_GPIO,  OUTPUT2_GPIO_PIN,  GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT3_GPIO,  OUTPUT3_GPIO_PIN,  GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT4_GPIO,  OUTPUT4_GPIO_PIN,  GPIO_PIN_RESET);

	HAL_GPIO_WritePin(OUTPUT5_GPIO,  OUTPUT5_GPIO_PIN,  GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT6_GPIO,  OUTPUT6_GPIO_PIN,  GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT7_GPIO,  OUTPUT7_GPIO_PIN,  GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT8_GPIO,  OUTPUT8_GPIO_PIN,  GPIO_PIN_RESET);

	HAL_GPIO_WritePin(OUTPUT9_GPIO,  OUTPUT9_GPIO_PIN,  GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT10_GPIO, OUTPUT10_GPIO_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT11_GPIO, OUTPUT11_GPIO_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT12_GPIO, OUTPUT12_GPIO_PIN, GPIO_PIN_RESET);

	HAL_GPIO_WritePin(OUTPUT13_GPIO, OUTPUT13_GPIO_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT14_GPIO, OUTPUT14_GPIO_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT15_GPIO, OUTPUT15_GPIO_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(OUTPUT16_GPIO, OUTPUT16_GPIO_PIN, GPIO_PIN_RESET);



	/* 配置OUTPUT GPIO:推挽输出模式 */
	GPIO_InitStruct.Pin   = OUTPUT1_GPIO_PIN;
	GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT1_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT2_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT2_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT3_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT3_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT4_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT4_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT5_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT5_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT6_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT6_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT7_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT7_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT8_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT8_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT9_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT9_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT10_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT10_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT11_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT11_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT12_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT12_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT13_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT13_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT14_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT14_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT15_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT15_GPIO, &GPIO_InitStruct); 

	GPIO_InitStruct.Pin = OUTPUT16_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(OUTPUT16_GPIO, &GPIO_InitStruct); 
}


void outputON(void)
{
	OUTPUT1_HIGH();
	OUTPUT2_HIGH();
	OUTPUT3_HIGH();
	OUTPUT4_HIGH();
	OUTPUT5_HIGH();
	OUTPUT6_HIGH();
	OUTPUT7_HIGH();
	OUTPUT8_HIGH();
	OUTPUT9_HIGH();
	OUTPUT10_HIGH();
	OUTPUT11_HIGH();
	OUTPUT12_HIGH();
	OUTPUT13_HIGH();
	OUTPUT14_HIGH();
	OUTPUT15_HIGH();
	OUTPUT16_HIGH();
}

void outputOFF(void)
{
	OUTPUT1_LOW();
	OUTPUT2_LOW();
	OUTPUT3_LOW();
	OUTPUT4_LOW();
	OUTPUT5_LOW();
	OUTPUT6_LOW();
	OUTPUT7_LOW();
	OUTPUT8_LOW();
	OUTPUT9_LOW();
	OUTPUT10_LOW();
	OUTPUT11_LOW();
	OUTPUT12_LOW();
	OUTPUT13_LOW();
	OUTPUT14_LOW();
	OUTPUT15_LOW();
	OUTPUT16_LOW();
}





